"""Fail-closed gate. Nothing is submittable unless this passes.

usage: python tools/gate.py p2 c1
Writes gate.json, and submission.md on pass.
"""
import json, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import cell_dir, cell_filled, log, mtime, now, verdict

REQUIRED_HEADERS = ["## Status:", "## Claim", "## Proof", "## Cited vs ours", "## What is not established"]
CLAIM_KEYS = ["statement", "deliverables", "acceptance_rules", "type"]
BANNED = [r"\bclearly\b", r"\bobviously\b", r"\broutine\b", r"it is easy to see", r"\bWLOG\b",
          r"without loss of generality", r"\bsimilarly\b", r"by symmetry"]


def gate(p, c):
    d = cell_dir(p, c)
    P = lambda *x: os.path.join(d, *x)
    reasons, warnings = [], []

    if not cell_filled(p, c):
        reasons.append("cell.md is still a placeholder")
    try:
        claim = json.load(open(P("claim.json")))
        for k in CLAIM_KEYS:
            if k not in claim:
                reasons.append(f"claim.json missing key {k}")
    except Exception as e:
        reasons.append(f"claim.json unreadable: {e}")

    status = None
    if not os.path.exists(P("proof.md")):
        reasons.append("no proof.md")
    else:
        proof = open(P("proof.md")).read()
        for h in REQUIRED_HEADERS:
            if h not in proof:
                reasons.append(f"proof.md missing section '{h}'")
        m = re.search(r"## Status:\s*(SOLVED|PARTIAL)", proof)
        status = m.group(1) if m else None
        if not status:
            reasons.append("proof.md status must be exactly SOLVED or PARTIAL")
        for b in BANNED:
            for hit in re.finditer(b, proof, re.I):
                line = proof[:hit.start()].count("\n") + 1
                warnings.append(f"proof.md line {line}: banned phrase '{hit.group(0)}' - verifier must have checked it")

    v = verdict(p, c)
    if v is None:
        reasons.append("review.md missing or last line is not 'VERDICT: PASS|FAIL'")
    elif v == "FAIL":
        reasons.append("verifier verdict is FAIL")
    rev_t = mtime(P("review.md"))
    for f in ["proof.md", "cert/search.py", "cert/certificate.json"]:
        ft = mtime(P(f))
        if ft and rev_t and ft > rev_t:
            reasons.append(f"{f} changed after review.md - needs a fresh review")

    cert_summary = None
    if os.path.exists(P("cert", "search.py")):
        if not os.path.exists(P("cert", "certificate.json")):
            reasons.append("cert/search.py exists but no certificate.json")
        rr = P("cert", "rerun.json")
        if not os.path.exists(rr):
            reasons.append("no cert/rerun.json - run tools/rerun.py")
        else:
            r = json.load(open(rr))
            if not r.get("ok"):
                reasons.append(f"rerun failed: {r.get('diffs')}")
            if mtime(P("cert", "certificate.json")) and mtime(rr) < mtime(P("cert", "certificate.json")):
                reasons.append("rerun.json older than certificate.json")
            cert = json.load(open(P("cert", "certificate.json")))
            for s in cert["sizes"]:
                if not s.get("certified"):
                    warnings.append(f"size {s['size']} NOT certified ({'unfinished' if not s.get('finished') else str(s.get('n_undecided')) + ' undecided survivors'}) - must not be claimed")
            if not cert.get("rules") and any(s.get("pruned") for s in cert["sizes"]):
                reasons.append("pruning without registered rules")
            cert_summary = {"certified_sizes": cert["certified_sizes"],
                            "nodes": {str(s["size"]): s["nodes"] for s in cert["sizes"]},
                            "total_wall_s": cert["total_wall_s"], "rerun_wall_s": r.get("wall_s")}

    ok = not reasons
    res = {"t": now(), "pass": ok, "status": status if ok else None, "verdict": v,
           "reasons": reasons, "warnings": warnings, "certificate": cert_summary}
    json.dump(res, open(P("gate.json"), "w"), indent=1)
    log(p, c, "gate", passed=ok, status=status, n_reasons=len(reasons))
    if ok:
        write_submission(p, c, status, cert_summary)
    return res


def write_submission(p, c, status, cert_summary):
    d = cell_dir(p, c)
    parts = [f"<!-- auto-generated by tools/gate.py for {p} {c}; status {status} -->",
             open(os.path.join(d, "proof.md")).read()]
    s = os.path.join(d, "cert", "search.py")
    if os.path.exists(s):
        parts += ["\n---\n## Appendix A — search code (`cert/search.py`)\n", "```python", open(s).read(), "```",
                  "\n## Appendix B — certificate summary\n", "```json", json.dumps(cert_summary, indent=1), "```",
                  "\nRerun: `python tools/rerun.py " + p + " " + c + "` (reproduces node counts exactly).\n"]
    open(os.path.join(d, "submission.md"), "w").write("\n".join(parts))


if __name__ == "__main__":
    r = gate(sys.argv[1], sys.argv[2])
    print(json.dumps(r, indent=1))
    sys.exit(0 if r["pass"] else 1)
